parameters:
  vending_machine.products:
    Coca-cola: 1.50
    Snickers: 1.20
    Lay's: 2.00
  vending_machine.coins: [ 0.01, 0.05, 0.10, 0.25, 0.50, 1.00 ]

services:
  app\commands\BuyProductCommand:
    public: true,
    arguments:
      $products: '%vending_machine.products%'
      $coins: '%vending_machine.coins%'
